<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>IdeasND - <?php echo $this->title; ?></title>
        <meta content="Ideas ND" name="author">
        <meta name="description" content="<?php echo $this->description; ?>">
        <meta name="keywords" content="Think together and share ideas">
        <?php
        echo $this->headLink()->appendStylesheet('/css/bootstrap.min.css')
                ->appendStylesheet('/css/bootstrap-theme.min.css')
                ->appendStylesheet('/css/jqvmap.css')
                ->appendStylesheet('/css/style.css');
        ?> 
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <link href="images/favicon.ico" rel="shortcut icon">
    </head>
    <body>



        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Ideas ND</a>
                </div>
                <div class="collapse pull-right navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Sign In</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>

        <div class="container">

                <div id="registermap" style="width: 100%; height: 500px;">

                </div>
            </div>

        </div><!-- /.container -->


        <div class="container">
            <footer>
                <p>&copy; IdeasNB <?php echo date('Y'); ?></p>
            </footer>
        </div> <!-- /container -->

        <?php echo $this->layout()->content; ?>
        <!-- Javascript  -->
        <?php
        echo $this->headScript()->appendFile('/js/jquery.js')
                ->appendFile('/js/bootstrap.min.js')
                //mvg MAPS
                ->appendFile('/js/jquery.vmap.js')
                ->appendFile('/js/jquery.vmap.world.js')
                ->appendFile('/js/jquery.vmap.sampledata.js')
                ->appendFile('/js/script.js');
        ?>
    </body>
</html> 